### ISSUE TITLE
Give a higher score to matches at the beginning of a path component?

### ISSUE THREAD

**Issue by sharplet** [calleerlandsson/pick#105]
Previously: Stable sorting?

~~Besides https://github.com/thoughtbot/pick.vim, my most common use case is a fuzzy project finder that sorts by most recent. However once I start typing, the original sort order appears to be lost.~~

~~I think the unstable sort probably makes sense as a default for performance reasons, but perhaps a stable sort option would be appropriate?~~

**Comment by calleerlandsson** [comment]
Hey, @sharplet! Thanks for your feedback.

What version of Pick are you running? From 1.3.0, the sorting should be stable.

**Comment by sharplet** [comment]
You know, I'm on 1.3.0, so perhaps stability isn't the problem!

Here's an example that didn't quite match my expectation:

![example search query with pick](https://cloud.githubusercontent.com/assets/147686/13477692/aeea17c4-e121-11e5-8a8f-3cf27d5a517a.PNG)

After typing the query `li`, the first result is "CLIKit", instead of something that _starts with_ "li", "liftoff".

Note that selecta exhibits the same behaviour:

![example search query with selecta](https://cloud.githubusercontent.com/assets/147686/13477816/452ff726-e122-11e5-9e10-9326fa86253a.PNG)

**Comment by calleerlandsson** [comment]
I see what you mean. The reason this happens is because the algorithm scores higher the shorter the total string is compared to the matching substring.

I'm not sure how we could improve the algorithm for this use case but I'd be happy to hear any suggestions! Pull requests are of course also very welcome.

**Comment by sharplet** [comment]
I think for the algorithm to follow my intuition, it would have to become aware of path components, and favour matches anchored to the beginning of a path component.

I took a dive into the source, but I think a PR is probably beyond me at this point (without some serious hand-holding).

**Comment by calleerlandsson** [comment]
Yes, something like that might work!

I'd be happy to answer all your questions and also to pair on this if we can find a time that works for both of us.

In the meantime, should we rename this issue or close it in favor of a future PR?

**Comment by sharplet** [comment]
I went ahead and renamed the issue for now. It would be cool if we could take a look at this at some time.

**Comment by calleerlandsson** [comment]
I'll go ahead and close this issue for now.

If anyone would like to take a stab at something like this, I think it's important to consider the fact that pick is also used to search for other things than file names. An alternative scoring algorithm would therefore have to be sufficiently general in order to be possible to merge.
