### ISSUE TITLE
Esc to exit

### ISSUE THREAD

**Issue by justgage** [calleerlandsson/pick#125]
I don't know about you guys but I use Pick primarily in Vim and I find it quite frustrating to not be able to exit it via ESC. I know very little about terminal programming but it seems like this would be possible and good. 

Just an idea.

**Comment by calleerlandsson** [comment]
Hey @justgage, thanks for your feedback!

The main problem with using escape to exit is that [other keys](https://github.com/thoughtbot/pick/blob/1bf6fb42b5220a217aba9c0e8f26cd9459011441/src/pick.c#L767-L777) (like the arrow keys) emit so called escape sequences instead of single characters. These escape sequences are so called because they start with the escape character (`\033`).

When reading the escape character there is (to my knowledge) no way of knowing whether it is the start of an escape sequence or if the user just pressed the escape key. Other programs solve this using timers. When the escape character is read, a timer is started and if no other character is read before the timer runs out, it is interpreted as the user pressing the escape key.

These timers could potentially add quite a bit of complexity to pick and that's why we have yet to introduce them. I'm not inherently opposed to the idea of using escape to exit the program but I haven't looked into exactly how much complexity would have to be introduced to support this.

What are your thoughts, @mptre, @mike-burns, @teoljungberg?

**Comment by mike-burns** [comment]
I'd also be happy with anything besides <kbd>ESC</kbd>. I see that <kbd><kbd>CTRL</kbd><kbd>C</kbd></kbd> works already -- we should add that to the man page.

**Comment by teoljungberg** [comment]
It's a convention in command line tools to exit them with `ctrl-c` (and `ctrl-d` for interactive programs). So I'm fine with sticking with `ctrl-c` to exit pick.

`ctrl-d` on the other hand could be interesting to explore. We could keep the existing behavior and using `ctrl-d` to delete a character if there is one and exiting only if there are no characters on the line.
I have no idea how difficult that would be to implement, or if it's inline with how we want `pick` to work.

Just a thought.

**Comment by mptre** [comment]
I find it annoying that `CTRL-D` is not interpreted as `EOF` by pick. However, I
don't think we should change it nor making its behavior context-aware. I'm fine
with `CTRL-C`.

**Comment by justgage** [comment]
So to clarify,  it's impossible to detect unambiguously without timers? It seems that from this (non-authoritative) answer they might be conflict with that: http://stackoverflow.com/a/34210745

Control-c is fine, I just find hard to context switch between vim and pick and it seemed to not effect any of the existing functionality.  Control-d would be nice too.

> I'd also be happy with anything besides ESC

Could you elaborate on why you feel this way? There must be something on missing.

**Comment by mike-burns** [comment]
Wikipedia has a detailed description but, unfortunately, no citation:

> If the Esc key and other keys that send escape sequences are both supposed to be meaningful to an application, an ambiguity arises if a character terminal is in use. When the application receives the ASCII escape character, it is not clear whether that character is the result of the user pressing the Esc key or whether it is the initial character of an escape sequence (e.g., resulting from an arrow key press). The traditional method of resolving the ambiguity is to observe whether or not another character quickly follows the escape character. If not, it is assumed not to be part of an escape sequence.

Feel free to try your hand at a patch to pick if you want to experience this firsthand.

> I'd also be happy with anything besides ESC

Sorry, I was ambiguous/rude: I meant that even if we can't get it working easily with <kbd>ESC</kbd>, we should document how people are supposed to quit pick. It looks like <kbd><kbd>Ctrl</kbd><kbd>C</kbd></kbd> is that answer currently.


My reading of this thread is: we're not opposed to using <kbd>ESC</kbd> to quit pick, we're not confident that it's straight-forward, and we'd welcome a patch demonstrating otherwise.

**Comment by justgage** [comment]
Ok sounds good, I might try my hand at it if time allows, I'm the meantime
thanks so much for this awesome tool :-).

**Comment by calleerlandsson** [comment]
Cool! Yeah, like @mike-burns said, we're happy to to review PRs and to answer questions so feel free to ping me.

I've opened #127 to resolve the confusion about <kbd><kbd>Ctrl</kbd><kbd>C</kbd></kbd>.

**Comment by justgage** [comment]
I tried working on it today. It does seem that the Wikipedia article is right (you can see this by typing <kbd>esc</kbd> + anything and watch it eat the characters).

One option is to support a _double_ <kbd>esc</kbd>. Seems a little clunky though so I'll probably only use it for my own purposes. 

The other option is to introduce some pthread stuff to make some sort of timer that could exit the current thread after a certain amount of time. But again, this would introduce quite a bit of complexity so is probably not worth it. You can mark this as closed if you guys/gals feel satisfied.

**Comment by mptre** [comment]
I don't advocate that that we should implement this, however here's
another proposal on how to detect a single `ESC`. Use poll to wait for a
limited amount of time until a file-descriptor is ready for reading. If
the timeout is reached before the fd being ready, terminate the current
process. Caution code not tested:

```c
if (buf[*nread - 1] == '\033') {
  struct pollfd pfd;
  pfd.fd = fileno(tty_in);
  pfd.events = POLLIN;
  if (poll(&pfd, 1, 200) == 0)
    kill(0, SIGINT);
}
```

**Comment by mptre** [comment]
Here's another interesting solution[1][2].

[1] https://github.com/antirez/kilo/blob/master/kilo.c#L223-L225
[2] https://github.com/antirez/kilo/blob/master/kilo.c#L247-L250

**Comment by DBOTW** [comment]
If someone is still interested in using `ESC` to exit: https://github.com/DBOTW/pick/tree/escape

**Comment by calleerlandsson** [comment]
Thanks for posting #223, @DBOTW! I think it's a great solution to the problem but I do agree with what @mptre wrote in [his comment](https://github.com/calleerlandsson/pick/pull/223#issuecomment-320450915):

> However, I'm not in favor of adding support for `ESC` since it's not too common among other Unix utilities [...]

To avoid any confusion I will close this issue now.
